language: node_js
node_js:
  - "6"
  - "7"
  - "8"

install: npm install

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: "build"
  on:
    branch: master